/// Flutter icons HealthDiaryIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HealthDiaryIcons
///      fonts:
///       - asset: fonts/HealthDiaryIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HealthDiaryIcons {
  HealthDiaryIcons._();

  static const _kFontFam = 'HealthDiaryIcons';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attribute = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawer = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entered_data = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData start = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_event = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
